server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: ecommerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://revatureprojects.cnplui1davyl.us-east-2.rds.amazonaws.com/postgres?currentSchema=ecommerce
    username: postgres
    password: qtR9681XaIOD
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
jwt:
  secret: XxUoNPRvzMVO6Ov2bLFFEGxQq1agFQKupCodqszMbndtknVt2eJ0j2PG1YLzRbUB70Mvw1ExKsl0S4rxWVIUdjhWePyH1fD3MxZ